server:
  port: ${SERVER_PORT}
spring:
  application:
    name: sesame-config-service
  cloud:
    config:
      server:
        native:
          search-locations: ${SPRING_CLOUD_SERVER_NATIVE_SEARCH_LOCATIONS}
  profiles:
    include: native
  security:
    user:
      password: sesame-config-service-user
      name: sesame-config-service-user
      roles: sesame-config-service-users
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/sesame-config-service
      client:
        registration:
          keycloak:
            client-id: sesame-config-service-client
            client-secret: 0WCGWVWcnGZKSOPJxmEzb2eZwVAMfl8x
            scope:
              - openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8180/realms/sesame-config-service
            jwk-set-uri: http://localhost:8180/realms/sesame-config-service/protocol/openid-connect/certs

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
