spring:
  r2dbc:
    url: r2dbc:mysql://${SESAME_USER_SERVICE_DB_HOSTNAME}/sesame-user-service
    username: ${SESAME_USER_SERVICE_DB_USERNAME}
    password: ${SESAME_USER_SERVICE_DB_PASSWORD}
    name: ${SESAME_USER_SERVICE_DB_NAME}
  flyway:
    url: jdbc:mysql://${SESAME_USER_SERVICE_DB_HOSTNAME}/${SESAME_USER_SERVICE_DB_NAME}
    password: ${SESAME_USER_SERVICE_DB_PASSWORD}
    user: ${SESAME_USER_SERVICE_DB_USERNAME}
    enabled: true
    baseline-on-migrate: true